### ISSUE TITLE
Appearance: Switch Background flexibility

### ISSUE THREAD

**Issue by andre68723** [holtwick/onepile#147]
onepile currently adopts color scheme to the macos appearance setting (dark mode/light mode)

- provide a additional switch to change content pane background color to light (for dark mode)

see https://supertekboy.com/2019/07/04/improved-dark-mode-in-outlook-for-windows/

**Comment by holtwick** [comment]
<img width="368" alt="CleanShot 2019-11-05 at 16 48 14@2x" src="https://user-images.githubusercontent.com/49557/68222973-36e73e80-ffec-11e9-9992-8d2e9c9bc128.png">
