### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by holtwick** [holtwick/onepile#20]
- [x] Import all supported text styles
- [ ] Import referenced resources as `media` and relate
- [ ] Identify duplicates #18 
- [x] Export, see also #19 
- [ ] TextBundle http://textbundle.org/spec/ #19 
- [x] Copy plain text as Markdown

**Comment by andrev68** [comment]
is  "Copy plain text as Markdown" suitable for manually importing Markdown into a new note? If yes, how does it work. C&P did not bring the expected result with 1058. Thanks

**Comment by holtwick** [comment]
@andrev68  If you copy text from a note it is already put to the pasteboard as plain text with Markdown formatting and some other Formats as HTML. Pasting is not yet fully supported.

Could you describe the action you would like to perform a little more? From which app you would like to copy and where to paste? I would like to reproduce the concrete steps. Thanks.

**Comment by andrev68** [comment]
please c&p from [chrome](https://raw.githubusercontent.com/holtwick/onepile/master/README.md) into a new note. I'd expect to either have it auto-recognized as MD and display formatted, or else, switch to a source view where I can insert the MD code

**Comment by holtwick** [comment]
I see. Is there any other app with rich text representation capable of doing that out of the box, that could provide as an example? Technically the problem is to recognize Markdown as such. 

Currently, I tend to implement different behaviors when being inside of triple ` / code block and when not being inside of such. But I agree, this is a required feature.

**Comment by andrev68** [comment]
No, not found any, even in [atom](https://discuss.atom.io/t/auto-detect-markdown-as-language-for-txt-files/33287/3). For files, the MD extension should do, for C&P adding a ["set grammar"](https://github.com/burodepeper/language-markdown/issues/133#issuecomment-247574169) looks handy.

PS: Eventually this is also a general question for default, some like rich text, some don't accept any  proprietary formats but just plain markdown

**Comment by holtwick** [comment]
- [ ] Parse and understand YAML headers like `title` and `date`
- [ ] Create attachments and link correctly
- [ ] Lists; nested
- [ ] Tables
- [ ] All styles
- [ ] Smart about links between imported files; map to internal links

**Comment by holtwick** [comment]
Markdown support is out for macOS, see https://onepile.app/en/blog/markdown

**Comment by holtwick** [comment]
Follow up at #116
