### ISSUE TITLE
Let me download my invoices from Amazon

### ISSUE THREAD

**Issue by simonCGN** [holtwick/onepile#80]
Please explain your idea to make the app better:

Let me download my invoices from Amazon as pdf. That would be great.

App Version Info:
de.holtwick.mac.Collect@0.9.6+1026 BaPUugaNQMudoU4TEccEIw

**Comment by holtwick** [comment]
The idea in general is good, but it is out of the scope of this app. There are existing online services that allow to do such downloads. OnePile can then be used to manage them.
