### ISSUE TITLE
iOS Action "add to onepile" 

### ISSUE THREAD

**Issue by andrev68** [holtwick/onepile#93]
iOS version misses the [action](https://developer.apple.com/design/human-interface-guidelines/ios/extensions/sharing-and-actions/) to add content from any app, e.g. browser to send it directly into onepile. would be a neat addition, as its commong for Notes, Google Keep a.s.o. 
PS: refering to the upper icon list from the apple doc

**Comment by holtwick** [comment]
I agree. This is going to be implemented for iOS 1.2.

**Comment by holtwick** [comment]
This is implemented in iOS 1.2 (review pending)
